=== ucv-cs/Tehnologii-Web/Tema3/inscriere.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT inscriere (candidat,obiectiv,optiuni)>
<!ATTLIST inscriere id CDATA #REQUIRED>
<!ATTLIST inscriere data CDATA #REQUIRED>
<!ELEMENT candidat (nume,prenume,sex,cetatenie,cnp,etnie,stare-civila,
                    domiciliu,contact,rezultate-bacalaureat,mentiuni)>
<!ELEMENT obiectiv (prioritate)+>
<!ELEMENT optiuni (cazare,limba-straina+,modul-psihopedagogic)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT cetatenie (#PCDATA)>
<!ELEMENT cnp (#PCDATA)>
<!ELEMENT etnie (#PCDATA)>
<!ELEMENT stare-civila (#PCDATA)>
<!ELEMENT domiciliu (tara,regiune,localitate,adresa)>
<!ELEMENT contact (email,telefon)>
<!ELEMENT rezultate-bacalaureat (disciplina)+>
<!ATTLIST rezultate-bacalaureat medie CDATA #REQUIRED>
<!ELEMENT mentiuni (#PCDATA)>
<!ELEMENT prioritate (facultate,specializare,forma-scolarizare,
                      frecventa)>
<!ATTLIST prioritate ordin (1|2) #REQUIRED>
<!ELEMENT cazare (#PCDATA)>
<!ELEMENT limba-straina (#PCDATA)>
<!ATTLIST limba-straina prioritate (1|2) #REQUIRED>
<!ELEMENT modul-psihopedagogic (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT regiune (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT disciplina (#PCDATA)>
<!ATTLIST disciplina denumire CDATA #REQUIRED>
<!ELEMENT facultate (#PCDATA)>
<!ELEMENT specializare (#PCDATA)>
<!ELEMENT forma-scolarizare (#PCDATA)>
<!ELEMENT frecventa (#PCDATA)>

=== ucv-cs/Tehnologii-Web/Tema3/formular_inscriere_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inscriere SYSTEM "inscriere.dtd">
<inscriere id="12" data="2021-05-16">
	<candidat>
		<nume>Petrescu</nume>
		<prenume>George</prenume>
		<sex>masculin</sex>
		<cetatenie>română</cetatenie>
		<cnp>1900212165790</cnp>
		<etnie>română</etnie>
		<stare-civila>căsătorit</stare-civila>
		<domiciliu>
			<tara>Italia</tara>
			<regiune>Toscana</regiune>
			<localitate>Asciano</localitate>
			<adresa>7FC9+JF Asciano</adresa>
		</domiciliu>
		<contact>
			<email>george.petrescu@gmail.com</email>
			<telefon>0721234765</telefon>
		</contact>
		<rezultate-bacalaureat medie="9.50">
			<disciplina denumire="limba și literatura română">10</disciplina>
			<disciplina denumire="matematică">10</disciplina>
		</rezultate-bacalaureat>
		<mentiuni />
	</candidat>
	<obiectiv>
		<prioritate ordin="1">
			<facultate>științe economice</facultate>
			<specializare>contabilitate</specializare>
			<forma-scolarizare>buget</forma-scolarizare>
			<frecventa>învățământ la distanță</frecventa>
		</prioritate>
		<prioritate ordin="2">
			<facultate>științe</facultate>
			<specializare>informatică</specializare>
			<forma-scolarizare>taxă</forma-scolarizare>
			<frecventa>cu frecvență</frecventa>
		</prioritate>
	</obiectiv>
	<optiuni>
		<cazare>da</cazare>
		<limba-straina prioritate="1">engleză</limba-straina>
		<limba-straina prioritate="2">italiană</limba-straina>
		<modul-psihopedagogic>nu</modul-psihopedagogic>
	</optiuni>
</inscriere>
